In [1]:
import math
import numpy as np
class Var:
    def __init__(self, value, children=None):
        self.value = value
        self.children = children or []
        self.grad = 0
    def __add__(self, other):
        return Var(self.value+other.value, [(1, self), (1, other)])
    def __radd__(self, other):
        return Var(self.value+other, [(1, self)])
    def __sub__(self, other):
        return Var(self.value-other.value, [(1, self), (-1, other)])
    def __mul__(self, other):
        return Var(self.value*other.value, [(other.value, self), (self.value, other)])
    def __truediv__(self, other):
        return Var(self.value/other.value, [(1/other.value, self), ((-1*self.value)/other.value**2, other)])
    def __neg__(self):
        return Var(-1*self.value, [(-1, self)])
    def sin(self):
        return Var(math.sin(self.value), [(math.cos(self.value), self)])
    def cos(self):
        return Var(math.cos(self.value), [(-1*math.sin(self.value), self)])
    def exp(self):
        return Var(math.exp(self.value), [(math.exp(self.value), self)])
    def backward(self, grad=1):
        self.grad += grad
        for coeff, child in self.children:
            child.backward(grad*coeff)

In [2]:
x = Var(10)
y = Var(2)
f = (x*x).sin().exp()
f.backward()
print(f.value)
print(x.grad)

0.602681965908778
10.394080663811636


In [3]:
def sigmoid(x):
    one = Var(1)
    ans = one/(one+(-x).exp())
    return ans

In [4]:
def tanh(x):
    e1 = x.exp()
    e2 = (-x).exp()
    return (e1-e2)/(e1+e2)

In [5]:
x = Var(45)
f = tanh(x)
f.backward()
print(f.value)
print(x.grad)

1.0
8.194012623990515e-40


In [6]:
x = Var(10)
f = sigmoid(x)
f.backward()
print(f.value)
print(x.grad)

0.9999546021312976
4.539580773595167e-05


In [7]:
print('without automatic differentiation')
print('e^(sin(x^2))')
x = 10
f = math.exp(math.sin(x**2))
df = math.exp(math.sin(x**2))*math.cos(x**2)*2*x 
print(f)
print(df)

print('sigmoid')
x = 10
s = 1/(1+math.exp(-x))
ds = s*(1-s)
print(s)
print(ds)

print('tanh')
x = 45
t = (math.exp(x)-math.exp(-x))/(math.exp(x)+math.exp(-x))
dt = 1-t**2
print(t)
print(dt)



without automatic differentiation
e^(sin(x^2))
0.602681965908778
10.394080663811636
sigmoid
0.9999546021312976
4.5395807735907655e-05
tanh
1.0
0.0


In [8]:
x = Var(25)
f = x.cos()
f.backward()
print(f.value)
print(x.grad)

0.9912028118634736
0.13235175009777303


In [9]:
(math.cos(25.1)-math.cos(24.9))/(25.1-24.9)

0.13213127411447845

In [10]:
triangle = np.array([[0,1,1],[1,0,1],[1,1,0]])
triangle.shape

(3, 3)

In [11]:
triangle.T

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [12]:
np.linalg.det(triangle)

2.0

In [13]:
np.linalg.inv(triangle)

array([[-0.5,  0.5,  0.5],
       [ 0.5, -0.5,  0.5],
       [ 0.5,  0.5, -0.5]])

In [14]:
np.dot(triangle, triangle)

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])